### PR TITLE
Applied your bugfix

### PR DESCRIPTION
**Pull request by gpcf**
The bugfix works, I tested it on the buildings where I had problems.

### CODE REVIEW

**Review by Splizard — COMMENTED** [review]
Can you verify that if there is a gap in your mineshaft, the lift won't be found?

**Comment by gpcf** [comment]
It finds the lift if there's a gap, the fix does not work.

**Comment by Splizard** [comment]
If I get the time, I'll look into it

**Comment by Splizard** [comment]
Should be fixed now.

**Pull request closed without merging**
